name: textql-backend
version: 0.1.0.0
description: Backend for TextQL web application
author: Your Name
maintainer: your.email@example.com
copyright: 2024

dependencies:
- base >= 4.7 && < 5
- scotty
- text
- aeson
- megaparsec
- sqlite-simple
- bytestring
- transformers
- mtl
- time

library:
  source-dirs: src

executables:
  textql-server:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N 